fix workflow

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -16,13 +16,29 @@ jobs:
           server-id: github
           cache: 'maven'
 
-      # TODO: compare new pom version to old pom version correctly
-      - name: Check pom.xml Version
+      - name: Set PR Maven Version
+        id: set_pr_maven_version
+        run: echo "PR_MAVEN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"
+
+      - name: Set Main Maven Version
+        id: set_main_maven_version
         run: |
           git fetch origin ${{ github.base_ref }}
-          git diff --quiet ${{ github.base_ref }} -- pom.xml || (echo "pom.xml has changed." && exit 0)
-          echo "No changes detected in pom.xml."
-          exit 1
+          git checkout ${{ github.base_ref }}
+          echo "MAIN_MAVEN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"
+
+      - name: Compare Maven Versions
+        run: |
+          pr_maven_version = ${{ steps.set_pr_maven_version.outputs.PR_MAVEN_VERSION }}
+          main_maven_version = ${{ steps.set_main_maven_version.outputs.MAIN_MAVEN_VERSION }}
+          
+          if [ "$pr_maven_version" != "$main_maven_version" ]; then
+            echo "New pom.xml version detected ($main_maven_version -> $pr_maven_version)."
+          else
+            echo "Invalid pom.xml version - a release already exists with this version."
+            exit 1
+          fi
 
       - name: Build with Maven
+        if: success()
         run: mvn clean package --file pom.xml
